export const TEACHER_PROFILE_REQUEST = "TEACHER_PROFILE_REQUEST";
export const TEACHER_PROFILE_SUCCESS = "TEACHER_PROFILE_SUCCESS";
export const TEACHER_PROFILE_FAILURE = "TEACHER_PROFILE_FAILURE";
export const UPDATE_TEACHER_PROFILE = "UPDATE_TEACHER_PROFILE";
export const CLEAR_TEACHER_PROFILE = "CLEAR_TEACHER_PROFILE";
